name: Test
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec
